databases:
  - name: my_app_db
    databaseName: my_app_database
    plan: free

services:
  - type: web
    name: my_app
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
