default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myapp_development
  username: islamhm # Your PostgreSQL username
  password: your_password
  host: localhost
  url: <%= ENV['DATABASE_URL'] %>
  port: 5432

test:
  <<: *default
  database: myapp_test
  username: islamhm # Same username as development
  password: # Leave blank if no password is required
  host: localhost # Use localhost instead of db for local development
  port: 5432

production:
  <<: *default
  database: veeqocsvvalidator
  username: veeqocsvvalidator_user
  password: njCaDal5pnJF7MSN2UlLSyMHc0ShWPVh
  host: dpg-ctp74tds78s73cvv390-a
  port: 5432
