default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myapp_development
  username: myuser
  password: mypassword
  host: db
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

test:
  <<: *default
  database: myapp_test
  username: myuser
  password: mypassword
  host: db
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
