default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myapp_development
  username: islamhm # Your PostgreSQL username
  password: your_password
  host: localhost
  port: 5432

test:
  <<: *default
  database: myapp_test
  username: islamhm # Same username as development
  password: # Leave blank if no password is required
  host: localhost # Use localhost instead of db for local development
  port: 5432

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
